# Generated by Django 4.2.2 on 2023-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='useStateVal',
        ),
        migrations.AddField(
            model_name='device',
            name='usage',
            field=models.CharField(choices=[('bool', 'bool'), ('float', 'float')], default='bool', max_length=7),
        ),
        migrations.AlterField(
            model_name='device',
            name='floatValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='device',
            name='modeOperation',
            field=models.CharField(choices=[('input', 'input'), ('output', 'output')], default='output', max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
