# Generated by Django 4.2.2 on 2023-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_hardware_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(choices=[('', ''), ('amps', 'amps'), ('volt', 'volt'), ('°C', '°C'), ('rpm', 'rpm')], default='', max_length=20),
        ),
    ]
