# Generated by Django 4.2.2 on 2023-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_device_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='modeOperation',
            field=models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT')], default='OUTPUT', max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinNumber',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
