# Generated by Django 4.2.2 on 2023-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_remove_device_id_alter_device_modeoperation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinNumber',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
