# Generated by Django 4.2.2 on 2023-06-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_alter_device_devicename_alter_device_pinnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinNumber',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
