# Generated by Django 4.2.2 on 2023-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_alter_device_devicename_alter_device_pinnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinNumber',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
