# Generated by Django 4.2.2 on 2023-06-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0008_device_id_alter_device_pinnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
