# Generated by Django 4.2.2 on 2023-06-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=200)),
                ('pinNumber', models.PositiveSmallIntegerField()),
                ('modeOperation', models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT')], default='OUTPUT', max_length=6)),
                ('unit', models.CharField(choices=[('', ''), ('amps', 'amps'), ('volt', 'volt'), ('°C', '°C'), ('rpm', 'rpm')], default='', max_length=20)),
                ('usage', models.CharField(choices=[('bool', 'bool'), ('float', 'float')], default='bool', max_length=7)),
                ('state', models.BooleanField(default=False)),
                ('floatValue', models.FloatField(default=0.0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entries', to='homeApp.hardware')),
            ],
        ),
    ]
