# Generated by Django 4.2.2 on 2023-06-08 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0010_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='floatValue',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
