# Generated by Django 4.2.2 on 2023-06-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_alter_device_floatvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entries', to='homeApp.hardware'),
        ),
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(choices=[('amps', 'amps'), ('volt', 'volt'), ('°C', '°C'), ('rpm', 'rpm')], default='amps', max_length=20),
        ),
    ]
