# Generated by Django 4.2.2 on 2023-06-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0012_alter_device_node_alter_device_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(choices=[('°', 'amps'), ('amps', 'amps'), ('volt', 'volt'), ('°C', '°C'), ('rpm', 'rpm')], default='amps', max_length=20),
        ),
    ]
